# Generated by Django 4.0.4 on 2022-05-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='start',
            name='info',
            field=models.JSONField(default={}),
        ),
    ]
