# Generated by Django 4.0.4 on 2022-06-01 16:26

from django.db import migrations


def init_config(apps, schema_editor):
    Config = apps.get_model('artistic', 'Config')
    Config.objects.get_or_create(key='event_id', defaults={'value':1})
    Config.objects.get_or_create(key='comp_id', defaults={'value':1})
    Config.objects.get_or_create(key='start_id', defaults={'value':"-1"})


class Migration(migrations.Migration):

    dependencies = [
        ('artistic', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(init_config),
    ]
