# Generated by Django 4.2.7 on 2024-01-08 10:31

from django.db import migrations, models
import django.db.models.deletion


def add_config_value(apps, schema_editor):
    Config = apps.get_model('artistic', 'Config')
    Config.objects.get_or_create(key='timetrack', defaults={'value':0})


class Migration(migrations.Migration):

    dependencies = [
        ('artistic', '0003_judge_isready_alter_competition_event_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='start',
            old_name='time',
            new_name='scheduled_time',
        ),
        migrations.AlterField(
            model_name='start',
            name='scheduled_time',
            field=models.DateTimeField(null=True, verbose_name='Geplante Zeit des Starts'),
        ),
        migrations.AddField(
            model_name='start',
            name='calculated_time',
            field=models.TimeField(null=True, verbose_name='Berechnete Zeit des Starts'),
        ),
        migrations.RunPython(add_config_value),
    ]
